### ISSUE TITLE
use on android (Termux app)

### ISSUE THREAD

**Issue by ingnelson** [calledit/dns-tunnler#1]
Hello .

i tried to install and run dns-tunnler on my UBUNTU VPS  as a server  with this commands :

git clone https://github.com/callesg/dns-tunnler.git
cd dns-tunnler
npm install native-dns@0.4.1 stdio
nodejs dnsProxyServer.js -d www.movistar.com.ni.zteclaro.tk -p 80 -v

ERROR:

module.js:328
    throw err;
    ^

Error: Cannot find module 'native-dns'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/root/dns-tunnler/dnsProxyServer.js:1:73)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)

can you give me the right command to install it on my ubuntu vps as a server , please .

one more question:
is it posible use Termux application on android to run as a client and connect to my dns-tunnler server on the VPS to create the tunnel similar to a VPN  ?
if it is posible can you tell how to do it , please ?

Note: Termux is an Android terminal application and Linux environment.
https://github.com/termux/termux-app

i will wait your answer.

**Comment by calledit** [comment]
native-dns was not installed properly by the npm command.

Why do you want to run it on port 80? Port 80 is for http.
Also your dns name needs to be a NS record not a A record.

If you can install nodejs in your termux environment it should work.

**Comment by calledit** [comment]
Closing due to lack of response.
